on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repo
        uses: actions/checkout@v4

      - name: SSH Connection
        run: |
            echo "${{ secrets.HOST_KEY }}" > private_key.pem
            chmod 400 private_key.pem

      - name: Test ssh 
        run: nc -vz ${{ secrets.HOST_IP }} 22

      - name: Debug SSH
        run: |
            echo "Trying to connect...."
            ssh -v -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.HOS_NAME }}@${{ secrets.HOST_IP }} exit

      - name: Deploy to VM server
        run: |
            ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.HOS_NAME }}@${{ secrets.HOST_IP }} <<EOF
              rm -rf codapp
              git clone https://github.com/andrii-br/new-project.git codapp/
              cd codapp/
              docker build -t myapp .
              docker-compose up 
              sleep 5
              docker ps -a
              curl -i http://localhost:5000/
            EOF